# Generated by Django 5.2.4 on 2025-07-09 05:38

from django.db import migrations

def create_default_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.get_or_create(name='Visiteur')
    Role.objects.get_or_create(name='Admin')

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles),
    ]
